-- Novas tabelas para v2
CREATE TABLE IF NOT EXISTS metas (
    id SERIAL PRIMARY KEY,
    mes TEXT UNIQUE NOT NULL,
    meta_e_ll_p NUMERIC DEFAULT 0,
    meta_e_ll_sf NUMERIC DEFAULT 0,
    meta_e_total NUMERIC DEFAULT 0,
    meta_s_ll_p NUMERIC DEFAULT 0,
    meta_s_ll_sf NUMERIC DEFAULT 0,
    meta_s_total NUMERIC DEFAULT 0,
    meta_total NUMERIC DEFAULT 0,
    meta_contrib NUMERIC DEFAULT 0
);

CREATE TABLE IF NOT EXISTS igreja_retiradas (
    id SERIAL PRIMARY KEY,
    mes TEXT UNIQUE NOT NULL,
    diz_e NUMERIC DEFAULT 0,
    diz_s NUMERIC DEFAULT 0,
    oferta NUMERIC DEFAULT 0,
    social NUMERIC DEFAULT 0,
    missao NUMERIC DEFAULT 0,
    total_igreja NUMERIC DEFAULT 0,
    ret_sandro NUMERIC DEFAULT 0,
    ret_outro NUMERIC DEFAULT 0,
    ret_outros NUMERIC DEFAULT 0,
    total_ret NUMERIC DEFAULT 0,
    obs_ret TEXT DEFAULT ''
);

ALTER TABLE apuracao ADD COLUMN IF NOT EXISTS e_lb NUMERIC DEFAULT 0;
ALTER TABLE apuracao ADD COLUMN IF NOT EXISTS e_de NUMERIC DEFAULT 0;
ALTER TABLE apuracao ADD COLUMN IF NOT EXISTS e_dizimo NUMERIC DEFAULT 0;
ALTER TABLE apuracao ADD COLUMN IF NOT EXISTS e_oferta NUMERIC DEFAULT 0;
ALTER TABLE apuracao ADD COLUMN IF NOT EXISTS e_social NUMERIC DEFAULT 0;
ALTER TABLE apuracao ADD COLUMN IF NOT EXISTS e_missao NUMERIC DEFAULT 0;
ALTER TABLE apuracao ADD COLUMN IF NOT EXISTS e_desp_pes NUMERIC DEFAULT 0;
ALTER TABLE apuracao ADD COLUMN IF NOT EXISTS e_ll_p NUMERIC DEFAULT 0;
ALTER TABLE apuracao ADD COLUMN IF NOT EXISTS e_sf_lb NUMERIC DEFAULT 0;
ALTER TABLE apuracao ADD COLUMN IF NOT EXISTS e_sf_de NUMERIC DEFAULT 0;
ALTER TABLE apuracao ADD COLUMN IF NOT EXISTS e_sf_dizimo NUMERIC DEFAULT 0;
ALTER TABLE apuracao ADD COLUMN IF NOT EXISTS e_sf_oferta NUMERIC DEFAULT 0;
ALTER TABLE apuracao ADD COLUMN IF NOT EXISTS e_sf_social NUMERIC DEFAULT 0;
ALTER TABLE apuracao ADD COLUMN IF NOT EXISTS e_sf_missao NUMERIC DEFAULT 0;
ALTER TABLE apuracao ADD COLUMN IF NOT EXISTS e_ll_sf NUMERIC DEFAULT 0;
ALTER TABLE apuracao ADD COLUMN IF NOT EXISTS e_total NUMERIC DEFAULT 0;
ALTER TABLE apuracao ADD COLUMN IF NOT EXISTS e_contrib_total NUMERIC DEFAULT 0;
ALTER TABLE apuracao ADD COLUMN IF NOT EXISTS s_lb NUMERIC DEFAULT 0;
ALTER TABLE apuracao ADD COLUMN IF NOT EXISTS s_de NUMERIC DEFAULT 0;
ALTER TABLE apuracao ADD COLUMN IF NOT EXISTS s_dizimo NUMERIC DEFAULT 0;
ALTER TABLE apuracao ADD COLUMN IF NOT EXISTS s_oferta NUMERIC DEFAULT 0;
ALTER TABLE apuracao ADD COLUMN IF NOT EXISTS s_social NUMERIC DEFAULT 0;
ALTER TABLE apuracao ADD COLUMN IF NOT EXISTS s_missao NUMERIC DEFAULT 0;
ALTER TABLE apuracao ADD COLUMN IF NOT EXISTS s_desp_pes NUMERIC DEFAULT 0;
ALTER TABLE apuracao ADD COLUMN IF NOT EXISTS s_ll_p NUMERIC DEFAULT 0;
ALTER TABLE apuracao ADD COLUMN IF NOT EXISTS s_sf_lb NUMERIC DEFAULT 0;
ALTER TABLE apuracao ADD COLUMN IF NOT EXISTS s_sf_de NUMERIC DEFAULT 0;
ALTER TABLE apuracao ADD COLUMN IF NOT EXISTS s_sf_dizimo NUMERIC DEFAULT 0;
ALTER TABLE apuracao ADD COLUMN IF NOT EXISTS s_sf_oferta NUMERIC DEFAULT 0;
ALTER TABLE apuracao ADD COLUMN IF NOT EXISTS s_sf_social NUMERIC DEFAULT 0;
ALTER TABLE apuracao ADD COLUMN IF NOT EXISTS s_sf_missao NUMERIC DEFAULT 0;
ALTER TABLE apuracao ADD COLUMN IF NOT EXISTS s_ll_sf NUMERIC DEFAULT 0;
ALTER TABLE apuracao ADD COLUMN IF NOT EXISTS s_total NUMERIC DEFAULT 0;
ALTER TABLE apuracao ADD COLUMN IF NOT EXISTS s_contrib_total NUMERIC DEFAULT 0;
ALTER TABLE apuracao ADD COLUMN IF NOT EXISTS total_grupo NUMERIC DEFAULT 0;
ALTER TABLE apuracao ADD COLUMN IF NOT EXISTS total_contrib NUMERIC DEFAULT 0;

ALTER TABLE metas DISABLE ROW LEVEL SECURITY;
ALTER TABLE igreja_retiradas DISABLE ROW LEVEL SECURITY;
